export enum TextFormatEnum {
  UNKNOWN = "UNKNOWN",
  BOLD = "BOLD",
  ITALIC = "ITALIC",
  STRIKETHROUGH = "STRIKETHROUGH",
  TITLE = "TITLE",
  HEADING = "HEADING",
  SUBHEADING = "SUBHEADING",
  BODY = "BODY",
  ORDERED_LIST = "ORDERED_LIST",
  UNORDERED_LIST = "UNORDERED_LIST",
}
